### ISSUE TITLE
g:black_macchiato_path setting is overwritten by plugin

### ISSUE THREAD

**Issue by Abemii** [smbl64/vim-black-macchiato#1]
Hi, thanks for the nice plugin.

I found that the setting of `g:black_macchiato_path` is not reflected,
even though it is set in my `init.vim`.

## Environment

- Neovim 0.6.1
- Vim-plug

## Expected behavior

If I set `g:black_macchiato_path` in my `init.vim`, `g:black_macchiato_path` in the plugin is set to it.

However, it is overwritten by the line 1 of plugin itself, if the plugin is loaded after `init.vim` is loaded.

```vim
let g:black_macchiato_path = "black-macchiato"  " <---- here

function s:RunBlackMacchiato() range
    let cmd = g:black_macchiato_path
    ....
```

## Proposal

```diff
--- a/plugin/black-macchiato.vim
+++ b/plugin/black-macchiato.vim
@@ -1,7 +1,5 @@
-let g:black_macchiato_path = "black-macchiato"
-
 function s:RunBlackMacchiato() range
-    let cmd = g:black_macchiato_path
+    let cmd = get(g:, 'black_macchiato_path', 'black-macchiato')
     if !executable(cmd)
         echohl ErrorMsg
         echom "black-macchiato not found!"
```

## Repro

The minimum `init.vim` is as follows.

```vim
filetype off

" auto-install vim-plug
if empty(glob($XDG_CONFIG_HOME . '/nvim/autoload/plug.vim'))
  silent !curl -fLo $HOME/.config/nvim/autoload/plug.vim --create-dirs 
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

" map leader
let mapleader = "\<Space>"

call plug#begin($XDG_CONFIG_HOME . '/nvim/plugged')
Plug 'smbl64/vim-black-macchiato'         " partial formatter for python
call plug#end()

autocmd FileType python xmap <buffer> <Leader>f <plug>(BlackMacchiatoSelection)
autocmd FileType python nmap <buffer> <Leader>f <plug>(BlackMacchiatoCurrentLine)
let g:black_macchiato_path = $HOME . '/.venv/bin/black-macchiato'  " black-macchiato is installed in virtual environment for neovim.

filetype plugin indent on
```

**Comment by smbl64** [comment]
Hello @Abemii. 

Apologies for the late reply. I _just_ saw this open issue! 

Thanks for investigating and proposing a solution. I would suggest that you open a pull request for this, because I see you have already fixed it in your fork. I will be happy to merge it! 😄 

Otherwise I can also fix it directly on `master`.

**Comment by Abemii** [comment]
hi @smbl64 , 

thank you for your reply!
ok, I will create an PR.

**Comment by Abemii** [comment]
hi @smbl64 ,

I have created an PR. Could you merge it if it seems good?

https://github.com/smbl64/vim-black-macchiato/pull/2
